TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
DB += basic_asyn_motor.db
DB += motorSim.substitutions
DB += sensor.db
DB += sensor.substitutions

REQ += basic_motor_settings.req
REQ += motor_positions.req
REQ += motorSim_settings.req
REQ += motorSim_positions.req
REQ += sensor.req
REQ += sensor_settings.req

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

